### PR TITLE
Use system wide installed eslint

### PR DESCRIPTION
**Pull request by doits**
I've had some issues with `eslintrb` because of it being a ruby wrapper. This means I cannot use all config options I'd normaly use with `eslint` (see https://github.com/zendesk/eslintrb/issues/5#issuecomment-227357968 for example).

I simply patched up `pronto-eslint` to use my system wide installed `eslint`. It calls the CLI of eslint and evaluates the output.

This of course means you have to install `eslint` by yourself with `npm`.

For now it simply fails if `eslint` is not present (but this can be made better, of course, with a nice error msg).

What do you think about this? Is this the way `pronto-eslint` wants to go? Or do you want to stay with `eslintrb`?

(note: I made this PR on top of my PR #7, which still enhances the `eslintrb`-version and should still be merged)

TODO:
- [ ] increment major version number and tell the world about the breaking changes
- [x] fix CI by installing eslint?

### CODE REVIEW

**Comment by mmozuras** [comment]
@doits if possible, I prefer not to count on people having `npm` 😄. Unless people vote that it's not an issue.

Maybe a separate gem makes sense here? There's nothing wrong with just having another runner.

**Comment by doits** [comment]
OK, done: https://github.com/doits/pronto-eslint_npm

**Comment by mmozuras** [comment]
@doits 👏 

You could make a PR to add it to the list in `pronto` README 😄

**Comment by doits** [comment]
https://github.com/mmozuras/pronto/pull/173

**Pull request closed without merging**
